"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const wallet_controller_1 = require("../controllers/wallet.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const router = (0, express_1.Router)();
router.get('/', auth_middleware_1.authenticate, wallet_controller_1.WalletController.getWallet);
router.get('/transactions', auth_middleware_1.authenticate, wallet_controller_1.WalletController.getTransactions);
router.post('/reward', auth_middleware_1.authenticate, wallet_controller_1.WalletController.claimAdReward);
router.post('/claim-rewarded-ad', auth_middleware_1.authenticate, wallet_controller_1.WalletController.claimAdReward);
exports.default = router;
